myproject/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('',views.HomePage.as_view(),name='homepage'),
    path('blog/',views.HomePage.as_view(),name='homepage'),
    path('blog/blogs/',views.BlogListView.as_view(),name='bloglistview'),
    path('blog/<int:pk>/',views.BlogDetailView.as_view(),name='blogdetailview'),
    path('blog/blogger/<int:pk>/',views.AuthorDetailView.as_view(),name='authordetailview'),
    path('blog/bloggers/',views.AuthorListView.as_view(),name='authorlistview'),
    path('blog/<int:pk>/create/',views.CommentPage,name='commentpage'),
    path('blog/add/', views.BlogCreateView.as_view(), name='blog_create'),
    path('author/add/', views.AuthorCreateView.as_view(), name='author_create'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('accounts/',include('user.urls')),
    # path('accounts/',include('django.contrib.auth.urls')),
]

myproject/user/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from . views import register_request,CustomLoginView

app_name = 'user'
urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('signup/',register_request,name='signup'),
    path('login/', CustomLoginView.as_view(), name='login')
]

myproject/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Base{% endblock %}</title>
    <style>
        body {
            font-family: "Lato", sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f2f2f2;
        }

        .navbar {
            background-color: #333;
            padding: 10px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            color: #f2f2f2;
        }

        .navbar h1 {
            margin: 0;
        }

        .navbar ul {
            list-style: none;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
        }

        .navbar ul li {
            margin-left: 15px;
        }

        .navbar ul li a {
            text-decoration: none;
            color: #f2f2f2;
        }

        .navbar ul li a:hover {
            color: #fff;
        }

        .user {
            color: white;
            font-size: 20px;
            margin: 10px 0;
            text-align: center;
        }

        /* Responsive Styles */
        @media screen and (max-width: 768px) {
            .navbar {
                flex-direction: column;
                align-items: flex-start;
                padding: 10px 20px;
            }

            .navbar ul {
                margin-top: 10px;
            }

            .navbar ul li {
                margin-left: 0;
                margin-bottom: 10px;
            }
        }
    </style>
    {% block extra_css %}
    {% endblock %}
</head>

<body>
    <div class="navbar">
        <h1>StorylineJunction</h1>
        <ul>
            <li><a href="{% url 'blog:bloglistview' %}">All Blogs</a></li>
            <li><a href="{% url 'blog:authorlistview' %}">Authors</a></li>
            <li><a href="{% url 'blog:homepage' %}">Home</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'user:logout' %}">Log Out</a></li>
            {% else %}
            <li><a href="{% url 'user:login' %}">Log In</a></li>
            <li><a href="{% url 'user:signup' %}">Sign Up</a></li>
            {% endif %}
        </ul>
    </div>

    <div id="main">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>