myproject/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('',views.HomePage.as_view(),name='homepage'),
    path('blog/',views.HomePage.as_view(),name='homepage'),
    path('blog/blogs/',views.BlogListView.as_view(),name='bloglistview'),
    path('blog/<int:pk>/',views.BlogDetailView.as_view(),name='blogdetailview'),
    path('blog/blogger/<int:pk>/',views.AuthorDetailView.as_view(),name='authordetailview'),
    path('blog/bloggers/',views.AuthorListView.as_view(),name='authorlistview'),
    path('blog/<int:pk>/create/',views.CommentPage,name='commentpage'),
    path('blog/add/', views.BlogCreateView.as_view(), name='blog_create'),
    path('author/add/', views.AuthorCreateView.as_view(), name='author_create'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('accounts/',include('user.urls')),
    # path('accounts/',include('django.contrib.auth.urls')),
]

myproject/blog/models.py
from django.db import models
from datetime import datetime

class Author(models.Model):
    name = models.CharField(max_length=100)
    about_author = models.TextField()

    def __str__(self):
        return self.name

class Blog(models.Model):
    author = models.ForeignKey(Author,on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    posted_date = models.DateTimeField(default=datetime.now())
    content = models.TextField()

    def __str__(self):
        return self.title

class Comment(models.Model):
    blog = models.ForeignKey(Blog,on_delete=models.CASCADE)
    comment_content = models.TextField()
    commented_date = models.DateTimeField(default=datetime.now())

    def __str__(self):
        return self.comment_content

myproject/blog/forms.py
from django import forms
from .models import Comment
from .models import Blog,Author

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_content']
        
class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'content', 'author']  # Customize this based on your Blog model fields

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['name','about_author']

myproject/blog/views.py
from typing import Any
from django.db import models
from django.views.generic import TemplateView,ListView,CreateView
from .models import Blog,Author,Comment
from django.shortcuts import render,redirect
from .forms import CommentForm
from django.contrib.auth.decorators import login_required
from .forms import BlogForm,AuthorForm
from django.urls import reverse_lazy

    
class HomePage(TemplateView):
    template_name = 'blog/homepage.html'


class BlogCreateView(CreateView):
    model = Blog
    form_class = BlogForm
    template_name = 'blog/blog_create.html'
    success_url = reverse_lazy('blog:bloglistview')  # Update the success_url

class AuthorCreateView(CreateView):
    model = Author
    form_class = AuthorForm
    template_name = 'blog/author_create.html'
    success_url = reverse_lazy('blog:authorlistview')  # Update the success_url

    
class BlogListView(ListView):
    template_name = 'blog/bloglistpage.html'
    queryset = Blog.objects.order_by('-posted_date')
    paginate_by = 5

class BlogDetailView(ListView):
    model = Comment
    template_name = 'blog/blogdetailpage.html'

    def get_queryset(self):
        queryset = super().get_queryset().filter(blog_id = self.kwargs['pk']).order_by('commented_date')
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["context"] = Blog.objects.filter(id = self.kwargs["pk"]).first()
        return context

class AuthorDetailView(ListView):
    model = Blog
    template_name = 'blog/authordetailpage.html'
    context_object_name = 'author_detail'
    
    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(author_id=self.kwargs["pk"]).order_by('-posted_date')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["context"] = Author.objects.filter(id=self.kwargs["pk"]).first()
        return context

class AuthorListView(ListView):
    template_name = 'blog/authorlistpage.html'
    queryset = Author.objects.all()

@login_required(login_url='/accounts/login/')
def CommentPage(request,pk):
    blog = Blog.objects.filter(pk=pk).first()
    if request.method == "POST":
        form = CommentForm(request.POST) 
        if form.is_valid():
            obj = form.save(commit=False)
            obj.blog_id = blog.pk
            obj.save()

            return redirect('blog:blogdetailview',pk)
    else:
        form = CommentForm()

    context = {
        'blog_' : blog,
        'form' : form,
    }            
    return render(request,'blog/commentcreatepage.html',context)

myproject/blog/templates/blog/author_create.html
{% extends 'base.html' %}

{% block title %}Create Author{% endblock %}

{% block content %}
  <h1>Create Author</h1>
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="{{ form.name.id_for_label }}">Name:</label>
      {{ form.name }}
    </div>
    <div class="form-group">
      <label for="{{ form.about_author.id_for_label }}">About Author:</label>
      {{ form.about_author }}
    </div>
    <button class="btn btn-primary" type="submit">Submit</button>
  </form>
{% endblock %}

{% block extra_css %}
<style>
  h1 {
    font-size: 24px;
    margin-bottom: 20px;
  }

  .form-group {
    margin-bottom: 20px;
  }

  label {
    font-weight: bold;
  }

  input[type="text"],
  textarea {
    width: 100%;
    padding: 8px;
    font-size: 16px;
    border-radius: 4px;
    border: 1px solid #ccc;
  }

  .btn-primary {
    background-color: #007bff;
    color: white;
    border: none;
    padding: 8px 16px;
    font-size: 16px;
    border-radius: 4px;
    cursor: pointer;
  }

  .btn-primary:hover {
    background-color: #0056b3;
  }

  .btn-primary:active {
    background-color: #00438a;
  }

  .btn-primary:focus {
    outline: none;
  }
</style>
{% endblock %}

myproject/blog/templates/blog/authordetailpage.html
{% extends 'base.html' %}

{% block title %}Author Detail Page{% endblock %}

{% block extra_css %}
<style>
    .header {
        padding: 10px;
        font-size: 25px;
        text-align: center;
    }

    .author {
        padding: 5px;
        font-size: large;
    }

    #aboutauthor {
        font-size: 30px;
        font-weight: bold;
    }

    .blog-list {
        margin-top: 20px;
    }

    .blog-list__item {
        display: flex;
        align-items: center;
        margin-bottom: 10px;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        background-color: #f8f8f8;
    }

    .blog-list__title {
        font-size: 18px;
        font-weight: bold;
        margin-right: 10px;
        flex: 1;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }

    .blog-list__date {
        font-size: 14px;
        color: #888;
        margin-right: 10px;
    }

    .blog-list__link {
        text-decoration: none;
        color: #007bff;
        font-size: 16px;
        transition: color 0.2s;
    }

    .blog-list__link:hover {
        color: #0056b3;
    }
</style>
{% endblock %}

{% block content %}
<div class="header">
    <h1>{{ context.name }}</h1>
</div>

<div class="author">
    <p id="aboutauthor">About Author:</p>
    <p>{{ context.about_author }}</p>
</div>

<div class="blog-list">
    <h3>Blogs by this author:</h3>
    {% for blog in author_detail %}
    <div class="blog-list__item">
        <h4 class="blog-list__title">{{ blog.title }}</h4>
        <span class="blog-list__date">{{ blog.posted_date }}</span>
        <a class="blog-list__link" href="{% url 'blog:blogdetailview' blog.id %}">Read more</a>
    </div>
    {% endfor %}
</div>
{% endblock %}

myproject/blog/templates/blog/authorlistpage.html
{% extends 'base.html' %}

{% block title %}Author List Page{% endblock %}

{% block extra_css %}
<style>
    h1 {
        color: #333;
        font-size: 28px;
        text-align: center;
        margin: 20px 0;
    }

    .author-list {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
        grid-gap: 20px;
        justify-items: center;
    }

    .author-card {
        background-color: #f8f8f8;
        border-radius: 8px;
        padding: 20px;
        text-align: center;
    }

    .author-name {
        font-size: 20px;
        font-weight: bold;
        margin-bottom: 10px;
    }

    .author-link {
        color: #007bff;
        text-decoration: none;
        font-size: 16px;
        transition: color 0.2s;
    }

    .author-link:hover {
        color: #0056b3;
    }

    .add-author-button {
        display: flex;
        justify-content: center;
        margin-top: 20px;
    }

    .add-author-link {
        background-color: #007bff;
        color: white;
        text-decoration: none;
        padding: 8px 16px;
        border-radius: 4px;
        transition: background-color 0.2s;
    }

    .add-author-link:hover {
        background-color: #0056b3;
    }
</style>
{% endblock %}

{% block content %}
<h1>Authors</h1>

<div class="author-list">
    {% for author in object_list %}
    <div class="author-card">
        <h2 class="author-name">{{ author.name }}</h2>
        <a class="author-link" href="{% url 'blog:authordetailview' author.id %}">View Author</a>
    </div>
    {% endfor %}
</div>

<div class="add-author-button">
    <a class="add-author-link" href="{% url 'blog:author_create' %}">Add Author</a>
</div>
{% endblock %}

myproject/blog/templates/blog/blog_create.html
{% extends 'base.html' %}
{% block title %}Create Blog{% endblock %}

{% block content %}
  <h1>Create Blog</h1>
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="{{ form.title.id_for_label }}">Title:</label>
      {{ form.title }}
    </div>
    <div class="form-group">
      <label for="{{ form.content.id_for_label }}">Content:</label>
      {{ form.content }}
    </div>
    <div class="form-group">
        <label for="{{ form.author.id_for_label }}">Author:</label>
        {{ form.author }}
      </div>
    <button class="btn btn-primary" type="submit">Submit</button>
  </form>
{% endblock %}

{% block extra_css %}
<style>
  h1 {
    font-size: 24px;
    margin-bottom: 20px;
  }

  .form-group {
    margin-bottom: 20px;
  }

  label {
    font-weight: bold;
  }

  input[type="text"],
  textarea {
    width: 100%;
    padding: 8px;
    font-size: 16px;
    border-radius: 4px;
    border: 1px solid #ccc;
  }

  .btn-primary {
    background-color: #007bff;
    color: white;
    border: none;
    padding: 8px 16px;
    font-size: 16px;
    border-radius: 4px;
    cursor: pointer;
  }

  .btn-primary:hover {
    background-color: #0056b3;
  }

  .btn-primary:active {
    background-color: #00438a;
  }

  .btn-primary:focus {
    outline: none;
  }
</style>
{% endblock %}

myproject/blog/templates/blog/blogdetailpage.html
{% extends 'base.html' %}
{% block title %}Blog Detail Page{% endblock %}
{% block extra_css %}
<style>
    .header {
        padding: 0px;
        font-size: 28px;
        text-align: center;
        background-color: #333;
        color: #fff;
        margin-bottom: 10px;
        border-radius: 5px;
    }

    p {
        font-size: 18px;
        line-height: 1.6;
        color: #333;
    }

    .date-writer {
        text-align: right;
        font-size: 16px;
        font-style: italic;
        margin-top: 0px;
        color: #888;
    }

    #comments {
        margin-top: 20px;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        background-color: #f0f0f0;
    }

    #comments > p {
        font-size: 24px;
        font-weight: bold;
        margin-bottom: 10px;
        color: #333;
    }

    #comments li {
        list-style-type: none;
        margin-bottom: 10px;
    }

    #comments li p {
        font-size: 16px;
        border: 1px solid #ccc;
        padding: 5px;
        border-radius: 5px;
        color: #333;
        background-color: #f9f9f9;
    }

    .below-content {
        margin-top: 10px;
        text-align: center;
    }

    .comment-link {
        text-decoration: none;
        font-size: 20px;
        color: #007bff;
        transition: color 0.2s;
    }

    .comment-link:hover {
        color: #0056b3;
        font-weight: bold;
    }
</style>
{% endblock %}

{% block content %}
<div class="header">
    <h1>{{ context.title }}</h1>
</div>

<div>
    <p class="date-writer"><span>Posted on:</span> {{ context.posted_date }}</p>
    <p>{{ context.content }}</p>
    <p class="date-writer"><span>Written by:</span> {{ context.author.name }}</p>
</div>

{% if object_list %}
<div id="comments">
    <p>Comments:</p>
    <ul>
        {% for com in object_list %}
        <li>
            <p>{{ com.comment_content }}</p>
            <span>{{ com.commented_date }}</span>
        </li>
        {% endfor %}
    </ul>
</div>
{% endif %}

<div class="below-content">
    <a class="comment-link" href="{% url 'blog:commentpage' context.id %}">Click here to add comments</a>
</div>
{% endblock %}

myproject/blog/templates/blog/bloglistpage.html
{% extends 'base.html' %}
{% block title %}Blog List Page{% endblock %}

{% block extra_css %}
<style>
    .container {
        display: flex;
        flex-wrap: wrap;
        justify-content: center; /* Updated to center-align the blogs */
        margin-top: 2rem;
    }

    .blog-list__item {
        width: 30%;
        margin-bottom: 2rem;
        box-shadow: 0px 0px 10px #ccc;
        border-radius: 5px;
        overflow: hidden;
        padding: 1rem;
    }

    .blog-list__item:hover {
        box-shadow: 0px 0px 5px #ccc;
    }

    .blog-list__title {
        font-size: 20px;
        font-weight: bold;
        margin-bottom: 10px;
        
    }
    .blog-list__title a{
        text-decoration: none;
        color: #007bff;
    }
    .blog-list__date {
        font-size: 14px;
        color: #888;
    }

    .blog-list__author {
        font-size: 16px;
        font-weight: bold;
        margin-top: 10px;
    }

    .pagination {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 2rem;
    }

    .pagination a {
        color: #007bff;
        text-decoration: none;
        font-size: 16px;
        transition: color 0.2s;
        margin: 0 5px;
    }

    .pagination a:hover {
        color: #0056b3;
        font-weight: bold;
    }

    .pagination .step-links {
        font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
        font-size: 40px;
        font-weight: bold;
        text-align: center;
        margin: 0 10px;
    }

    .add-blog-button {
        display: flex;
        justify-content: flex-end;
        margin-top: 1rem;
    }

    .add-blog-button .btn {
        background-color: #007bff;
        color: white;
        border: none;
        padding: 10px 20px;
        font-size: 16px;
        border-radius: 4px;
        cursor: pointer;
        transition: background-color 0.2s;
        text-decoration: none;
    }

    .add-blog-button .btn:hover {
        background-color: #0056b3;
    }

    .add-blog-button .btn:active {
        background-color: #00438a;
    }

    .add-blog-button .btn:focus {
        outline: none;
    }
    
    @media (max-width: 768px) {
        .blog-list__item {
            width: 100%;
        }
    }
</style>
{% endblock %}

{% block content %}
<div class="add-blog-button">
    <a href="{% url 'blog:blog_create' %}" class="btn btn-primary">Add Blog</a>
</div>

<h1 style="text-align: center;">Blogs</h1> <!-- Updated to center-align the heading -->

<div class="container">
    {% for blog in page_obj %}
    <div class="blog-list__item">
        <h2 class="blog-list__title"> <a href="{% url 'blog:blogdetailview' blog.id %}"> {{ blog.title }}</a></h2>
        <span class="blog-list__date">{{ blog.posted_date }}</span>
        <p class="blog-list__author">
            <a class="link-update" href="{% url 'blog:authordetailview' blog.author_id %}">{{ blog.author }}</a>
        </p>
    </div>
    {% endfor %}
</div>

<div class="pagination">
    <footer>
        {% if page_obj.has_previous %}
        <a class="link-update" href="?page=1">&laquo; first</a>
        <a class="link-update" href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="step-links">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a class="link-update" href="?page={{ page_obj.next_page_number }}">next</a>
        <a class="link-update" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </footer>
</div>
{% endblock %}

myproject/blog/templates/blog/commentcreatepage.html
{% extends 'base.html' %}
{% block title %}Comment Create Page{% endblock %}
{% block extra_css %}
<style>
    /* Form Container */
    form {
        width: 80%;
        margin: 2rem auto;
        padding: 2rem;
        border-radius: 10px;
        background-color: #f5f5f5;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    /* Form Label */
    label {
        font-size: 1.2rem;
        font-weight: bold;
        margin-bottom: 0.5rem;
        display: block;
    }

    /* Form Input */
    input[type="text"],
    textarea {
        width: 100%;
        padding: 0.5rem;
        margin-bottom: 1.5rem;
        border: 1px solid #ccc;
        border-radius: 5px;
        font-size: 1.2rem;
        background-color: #fff;
        transition: border-color 0.2s;
    }

    input[type="text"]:focus,
    textarea:focus {
        outline: none;
        border-color: #007bff;
        box-shadow: 0 0 0 2px rgba(0, 123, 255, 0.25);
    }

    /* Form Submit Button */
    input[type="submit"] {
        background-color: #007bff;
        color: #fff;
        padding: 0.75rem 1.5rem;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 1.2rem;
        transition: background-color 0.2s;
    }

    /* Form Submit Button - Hover */
    input[type="submit"]:hover {
        background-color: #0056b3;
    }
</style>
{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <label for="blog_title">Title:</label>
    <input type="text" name="blog_title" id="blog_title" value="{{ blog_.title }}" size="100%" disabled><br><br>
    <label for="blog_content">Content:</label>
    <textarea name="blog_content" id="blog_content" rows="5" cols="60" disabled>{{ blog_.content }}</textarea><br><br>
    <label for="posted_date">Posted Date:</label>
    <input type="datetime" name="posted_date" id="posted_date" value="{{ blog_.posted_date }}" disabled><br><br>
    {{ form }} <br><br>
    <input class="openbtn" type="submit" value="Post Comment">
</form>
{% endblock %}

myproject/blog/templates/blog/homepage.html
{% extends 'base.html' %}
{% block title %}Home Page{% endblock %}
{% block extra_css %}
<style>
    .homepage {
        text-align: center;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }

    .homepage h1 {
        font-size: 50px;
        margin-bottom: 20px;
        color: #333;
    }

    .homepage p {
        font-size: 18px;
        font-family: 'Times New Roman', Times, serif;
        margin-bottom: 10px;
    }
</style>
{% endblock %}

{% block content %}
<div class="homepage">
    <h1>Welcome {{ user.name }}!</h1>
    <p>Thank you for visiting our blog. We're glad you're here and excited to share our thoughts and experiences with you.
        Our blog is dedicated to providing valuable and informative content on a variety of topics including travel,
        personal development, and more.</p>
    <p>We believe that everyone has a unique perspective to share and we welcome you to share your own thoughts and
        experiences in the comments section of our posts.</p>
    <p>Again, welcome to our blog. We hope you enjoy reading our posts and find them informative and inspiring.</p>
</div>
{% endblock %}